# Generated by Django 3.2.19 on 2023-06-30 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservationtable',
            fields=[
                ('table_number', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking_app.reservationtable')),
            ],
        ),
    ]
