# Generated by Django 3.2.19 on 2023-06-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservationtable',
            new_name='Table',
        ),
    ]
